### ISSUE TITLE
donkey: could not establish connection: Connection refused (DinD build process, nvidia-driver GPU)

### ISSUE THREAD

**Issue by AntonioCayulao** [3XX0/donkey#3]
Hi!
I have an issue trying to sign nvidia drivers with these lines:
```shell
    if [ -n "${PRIVATE_KEY}" ]; then
        echo "Signing NVIDIA driver kernel modules..."
        donkey get "${PRIVATE_KEY}" sh -c "PATH=${PATH}:/usr/src/linux-headers-${KERNEL_VERSION}/scripts && \
          sign-file sha512 \$DONKEY_FILE pubkey.x509 nvidia.ko nvidia.ko.sign &&                          \
          sign-file sha512 \$DONKEY_FILE pubkey.x509 nvidia-modeset.ko nvidia-modeset.ko.sign &&          \
          sign-file sha512 \$DONKEY_FILE pubkey.x509 nvidia-uvm.ko"
        nvidia_sign_args="--linked-module nvidia.ko --signed-module nvidia.ko.sign"
        nvidia_modeset_sign_args="--linked-module nvidia-modeset.ko --signed-module nvidia-modeset.ko.sign"
        nvidia_uvm_sign_args="--signed"
    fi
```
The source code doesn't come from me, I'm just trying to compile and sign the drivers by myself based on the work done by the nvidia team because those are not available to ubuntu23.10 for now.

The documentation doesn't say anything related to donkey but, it's into the file nvidia-drivers:
https://download.nvidia.com/XFree86/Linux-x86/361.45.11/README/installdriver.html#modulesigning

I'm trying to run the docker build process like this:
```shell
 docker build  --network=host  -t <private-registry>/gen-driver:535.129.03-ubuntu23.10 -f generate_drivers.dockerfile  .
```
In my dockerfile named generate_drivers.dockerfile I have this related to donkey:
```Dockerfile
RUN /tmp/install.sh reposetup && /tmp/install.sh depinstall && \
    curl -fsSL -o /usr/local/bin/donkey https://github.com/3XX0/donkey/releases/download/v1.1.0/donkey && \
    chmod +x /usr/local/bin/donkey
# (...)
RUN /usr/local/bin/nvidia-driver init
```
The last RUN execution triggers many things and when it reach out the if statement pasted on top fails saying:
```shell
#0 30.13 Signing NVIDIA driver kernel modules...
#0 30.13 donkey: could not establish connection: Connection refused
```
I don't have docker utility in the host with the GPU so I'm creating the container using a DinD manifest for it:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dind-nvidia-driver
  namespace: default
spec:
  hostNetwork: true
  containers:
  - image: docker:24.0.0-rc.1-dind
    name: dind
    securityContext:
      privileged: true
    resources: {}
    volumeMounts:
    - name: repo-drivers
      mountPath: "/drivers"
  volumes:
  - name: repo-drivers
    hostPath:
      path: /home/user/dind
```
Could you help me to fix this issue, please?
